denimgroup/threadfix

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/GRCControl.java

to prevent any future serialization from creating an infinite recursion

Removing JsonView from Vulnerability property in GRCControl

---

threadfix-scanner-plugin/zaproxy/assembly/assembly.xml
threadfix-scanner-plugin/zaproxy/assembly/zap.xml
threadfix-scanner-plugin/zaproxy/pom.xml
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/action/EndpointsAction.java
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/action/ImportAction.java
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/action/LocalEndpointsAction.java
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/action/RemoteEndpointsAction.java
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/dialog/ConfigurationDialogs.java
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/dialog/SourceDialog.java
threadfix-scanner-plugin/zaproxy/src/org/zaproxy/zap/extension/threadfix/ThreadFixExtension.java
threadfix-scanner-plugin/zaproxy/src/org/zaproxy/zap/extension/threadfix/ZapPropertiesManager.java

Added HAM support to the Threadfix ZAP plugin so that endpoints can be generated from local code.
Updated the plugin's pom.xml to properly generate a ZAP plugin file.
Moved the threadfix.properties file to the ZAP Home folder.

Dgtf 997 add ham to threadfix zap plugin

---

threadfix-scanner-plugin/zaproxy/src/org/zaproxy/zap/extension/threadfix/ZapAddOn.xml

ZAP 2.3.1 loaded the addon despite this mistake. The latest ZAP weekly build (2.4) will not load the addon with the incorrect extension name.

Fixed the fully qualified path for ThreadFixExtension in ZapAddOn.xml.

---

pom.xml
threadfix-main/pom.xml
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/ToolsDownloadController.java
threadfix-main/src/main/webapp/WEB-INF/views/config/download/index.jsp
threadfix-main/src/main/webapp/WEB-INF/web.xml
threadfix-main/src/main/webapp/common/header.jsp

pom.xml, Rearrange build order of modules.
threadfix-main/pom.xml, Maven-ant-plugin to copy jars to target/classes/downloads folder.
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/ToolsDownloadController.java, Controller for Tools Download page.
threadfix-main/src/main/webapp/WEB-INF/views/config/download/index.jsp, View for Tools Download page.
threadfix-main/src/main/webapp/WEB-INF/web.xml, Add configuration/download to entryPoints.
threadfix-main/src/main/webapp/common/header.jsp, Add Download Tools page to Cog menu.

Dgtf 991 add tools download page

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/forms/addScheduledJobFields.jsp
threadfix-main/src/main/webapp/WEB-INF/views/applications/forms/addScheduledJobForm.jsp
threadfix-main/src/main/webapp/WEB-INF/views/applications/forms/addScheduledScanForm.jsp

This adds an ID to the error on these forms to help the related tests find the element more easily.

Added ID to the dateError on scheduled update and import forms

---

threadfix-main/src/main/webapp/WEB-INF/views/config/remoteproviders/configure.jsp
threadfix-main/src/main/webapp/scripts/filters.js

This creates a filter to replace whitespace from IDs for Remote Provider configuration modals.  This will help tests find the elements with less difficulty.

Created a filter to remove spaces from bindings

---

threadfix-cli/src/main/java/com/denimgroup/threadfix/cli/CommandLineParser.java
threadfix-cli/src/main/java/com/denimgroup/threadfix/cli/OptionsHolder.java
threadfix-cli/src/main/java/com/denimgroup/threadfix/remote/ThreadFixRestClient.java
threadfix-cli/src/main/java/com/denimgroup/threadfix/remote/ThreadFixRestClientImpl.java
threadfix-main/src/main/java/com/denimgroup/threadfix/service/VulnerabilityCommentServiceImpl.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/rest/VulnerabilityRestController.java
threadfix-service-interfaces/src/main/java/com/denimgroup/threadfix/service/VulnerabilityCommentService.java

Implemented by second solution: API keys needs to be attached with user.
Usage: -ac <vulnId> <comment> <[commentTagIds]>
CommentTagIds is optional, separated by comma.

DGTF-1214 Expose Comment submission in the REST API

---

threadfix-main/src/main/webapp/scripts/filters.js

This filter can be used to remove non-word characters from IDs, and will be used for elements such as email addresses.

Added a filter to remove non-word characters

---

threadfix-data-access/src/main/java/com/denimgroup/threadfix/data/dao/hibernate/HibernateChannelSeverityDao.java
threadfix-importers/src/main/resources/mappings/scanner/appscan.csv
threadfix-importers/src/main/resources/mappings/scanner/codeprofiler.csv
threadfix-importers/src/main/resources/mappings/scanner/manual.csv

MySQL is case insensitive query, that's why when run scanner mapping updater, it overrides "Critical" to "critical"

DGTF-1899 No "Critical" severity for Manual Findings in MySQL

---

threadfix-main/src/main/webapp/scripts/services.js

DGTF-2003 Dependency Check vulnerabilities appear twice in OWASP Top 10 report
DGTF-1977 Imported Sonatype vulnerabilities listed twice in OWASP Top 10 report

Stable-bugfix

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/tabs/scanTab.jsp

Small update to give the "Delete Scan" buttons on the application detail page IDs for tests to use.

Added IDs to delete buttons in scans tab

---

threadfix-main/src/main/webapp/WEB-INF/views/config/systemSettings.jsp

Set width on SELECT drop downs to not truncate report names.

DGTF-2017 Report Dropdown Cuts Off Part of Report Name on System Settings Page

---

threadfix-main/src/main/webapp/WEB-INF/views/vulnerabilities/vulnTreeVulnRows.jsp

These changes allow the badges to use the Vulnerability index instead of the badge index in the ID.  They also adjust the names used for the IDs to allow help tests find them.

Reworked IDs for tags and channels to remove duplicates

---

threadfix-main/src/main/java/com/denimgroup/threadfix/service/ManualFindingServiceImpl.java

When processing a manual finding, increment the counter for the severity (Critical, High, Medium, Low, Info).

DGTF-1656 Scan index page does not show count by severity for Manual Findings

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/tabs/scanQueueTab.jsp
threadfix-main/src/main/webapp/WEB-INF/views/applications/tabs/scheduledScanTab.jsp

This will help tests distinguish between the tables and locate them more efficiently.

Updates a few IDs for the Scan Agent Task and Scheduled Scan tabs

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/vulnComments.jsp
threadfix-main/src/main/webapp/WEB-INF/views/tags/commentTable.jsp

This push allows tests to find the comment tags attached to vulnerability comments.  The same tag could appear in multiple comments for the same vulnerability and in multiple vulnerabilities in the tree and will still have a unique ID.

Adds unique IDs to comment fields in vulnerability trees

---

threadfix-main/src/main/resources/threadfix-backup.script

This change is for the sake of the default database sent out with Zip Distributions of ThreadFix.

Changes Jira to JIRA

---

threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/rest/ApplicationRestController.java

Revert ../rest/../upload to be compatible with 2.2
Add new endpoint ../rest/.../upload/multi to upload multiple files

DGTF-2572 The scan upload REST endpoint is not backwards compatible

---

threadfix-main/src/main/webapp/WEB-INF/views/config/logs.jsp

Selenium tests cannot locate an element by ID if it starts with a number.

Corrects IDs on page to not start with numbers

---

threadfix-data-access/src/main/java/com/denimgroup/threadfix/data/dao/GenericSeverityDao.java
threadfix-data-access/src/main/java/com/denimgroup/threadfix/data/dao/hibernate/HibernateGenericSeverityDao.java
threadfix-main/src/main/java/com/denimgroup/threadfix/service/GenericSeverityServiceImpl.java

Allows a severity name to be changed to any name that is not currently in use.

DGTF-2636 allow rename to non-used names

---

threadfix-main/src/main/webapp/scripts/report/report-filter-controller.js

Prevents a saved filter from overwriting the tags needed for compliance filtering.

DGTF-2602 fix compliance filtering

---

threadfix-importers/src/main/java/com/denimgroup/threadfix/importer/impl/remoteprovider/ContrastRemoteProvider.java
threadfix-importers/src/main/resources/mappings/remoteprovider/contrast.csv

if contrast remote provider url is null it will now use the default url

null checked url and added placeholder

---

threadfix-main/src/main/webapp/scripts/filters.js

The comment elements on a Vulnerability Detail page did not have pivot information to pass in, so this filter was trying to replace text that didn't exist.  This led to errors that prevented the elements from having any value display for their ID.

Corrects error in filter used for IDs

---

threadfix-scanner-plugin/zaproxy/pom.xml

Version 3.2.1 has a CVSS 10.0 vulnerability. That is the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8103
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

Upgrade Apache Commons Collections to v3.2.2
