threadfix-main/src/main/java/com/denimgroup/threadfix/service/defects/JiraDefectTracker.java
threadfix-main/src/main/webapp/WEB-INF/views/defects/mergeDefectForm.jsp

mergeDefectForm.jsp modified so Select Defect is typeahead input field instead of select dropdown. 
JiraDefectTracker.getDefectList() modified to loop getting JSON until all JIRA defects are retrieved if total exceeds maxResults.

DGTF-1012 merge defect jira list

---

threadfix-scanner-plugin/burp/pom.xml
threadfix-scanner-plugin/burp/src/main/java/burp/BurpExtender.java
threadfix-scanner-plugin/burp/src/main/java/burp/custombutton/EndpointsButton.java
threadfix-scanner-plugin/burp/src/main/java/burp/custombutton/ExportButton.java
threadfix-scanner-plugin/burp/src/main/java/burp/custombutton/LocalEndpointsButton.java
threadfix-scanner-plugin/burp/src/main/java/burp/custombutton/RemoteEndpointsButton.java
threadfix-scanner-plugin/burp/src/main/java/burp/dialog/ApplicationDialog.java
threadfix-scanner-plugin/burp/src/main/java/burp/dialog/ConfigurationDialogs.java
threadfix-scanner-plugin/burp/src/main/java/burp/dialog/SourceDialog.java
threadfix-scanner-plugin/burp/src/main/java/burp/dialog/UrlDialog.java
threadfix-scanner-plugin/burp/src/main/java/burp/extention/BurpPropertiesManager.java
threadfix-scanner-plugin/burp/src/main/java/burp/extention/RestUtils.java

Added HAM support to ThreadFix Burp plugin. Updated the plugin to use the Burp GUI instead of just prompting the user with pop-ups. Also updated to store threadfix options as Burp extension settings.

Added HAM support to ThreadFix Burp plugin.

---

threadfix-main/src/main/webapp/WEB-INF/views/config/roles/form.jsp

Pull this ID change into stabilization branch.

git pull DGTF 1139 into stabilization

---

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/ChannelVulnerability.java
threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/Finding.java
threadfix-main/src/main/java/com/denimgroup/threadfix/service/ManualFindingServiceImpl.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/EditManualFindingController.java

Edit Manual Finding modal now displays current finding information. Submit Finding button saves changes.

Dgtf 987 unable edit manual finding

---

threadfix-cli/src/main/java/com/denimgroup/threadfix/remote/PluginClient.java
threadfix-scanner-plugin/zaproxy/pom.xml
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/ThreadFixApi.java
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/action/EndpointsAction.java
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/action/ImportAction.java
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/action/LocalEndpointsAction.java
threadfix-scanner-plugin/zaproxy/src/com/denimgroup/threadfix/plugin/zap/action/RemoteEndpointsAction.java
threadfix-scanner-plugin/zaproxy/src/org/zaproxy/zap/extension/threadfix/AbstractZapPropertiesManager.java
threadfix-scanner-plugin/zaproxy/src/org/zaproxy/zap/extension/threadfix/ThreadFixExtension.java
threadfix-scanner-plugin/zaproxy/src/org/zaproxy/zap/extension/threadfix/ZapApiPropertiesManager.java
threadfix-scanner-plugin/zaproxy/src/org/zaproxy/zap/extension/threadfix/ZapPropertiesManager.java

4 API calls were added:
- listThreadFixApplications
- importEndpointsFromThreadFix
- exportScan
- importEndpointsFromSource

Added API support to the ThreadFix ZAP plugin.

---

README.md

Updates the wiki link for the "Development Environment Setup" in the README.

Updates Dev Environment Setup wiki link in README.

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/forms/addScanQueueForm.jsp
threadfix-main/src/main/webapp/WEB-INF/views/applications/forms/addScheduledScanForm.jsp
threadfix-main/src/main/webapp/scripts/modal-controller-with-config.js

Same problem with scheduled scan

DGTF-1541 Form fields are reset after uploading file to scan agent task

---

threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/VulnerabilitySearchController.java
threadfix-main/src/main/webapp/scripts/report/report-services.js

DGTF-1681 Most of Export PDF buttons in Snapshot die

---

threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/ScanController.java

Was able to upload "Online Scan 20Dec2014.xml" and view without crash with MySQL and HSQLDB.

Added @JsonView to methods: scanTable and getBaseObjects.

---

threadfix-main/src/main/java/com/denimgroup/threadfix/service/queue/QueueConstants.java
threadfix-main/src/main/java/com/denimgroup/threadfix/service/queue/QueueListener.java
threadfix-main/src/main/java/com/denimgroup/threadfix/service/queue/QueueSenderImpl.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/ApplicationsController.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/TeamDetailPageController.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/VulnerabilityTabController.java
threadfix-main/src/main/webapp/WEB-INF/views/organizations/detail.jsp
threadfix-main/src/main/webapp/WEB-INF/views/vulnerabilities/vulnSearchControls.jsp
threadfix-main/src/main/webapp/WEB-INF/views/vulnerabilities/vulnTreeGroupHeader.jsp
threadfix-main/src/main/webapp/WEB-INF/views/vulnerabilities/vulnTreeVulnRows.jsp
threadfix-main/src/main/webapp/WEB-INF/web.xml
threadfix-main/src/main/webapp/scripts/application-page-modal-controller.js
threadfix-main/src/main/webapp/scripts/bulk-operations-controller.js
threadfix-main/src/main/webapp/scripts/vuln-search-controller.js
threadfix-service-interfaces/src/main/java/com/denimgroup/threadfix/service/queue/QueueSender.java

Similar to App Detail page, now user can mark/unmark false positive, close/open, batch tag/comment for vulns from Team detail Page

DGTF-1510 Add ability to mark false positives from the Team page

---

threadfix-cli-importers/src/test/java/com/denimgroup/threadfix/importer/parser/W3afScanTest.java
threadfix-importers/src/main/java/com/denimgroup/threadfix/importer/impl/upload/W3afChannelImporter.java
threadfix-importers/src/main/resources/mappings/scanner/w3af.csv

The W3af scanner changed the XML report file format (from ver. 2.0 to ver. 2.1). XML elements names changed and new ones were introduced.

Dgtf 1325 update w3af channel importer for version 2.1

---

threadfix-data-access/src/main/java/com/denimgroup/threadfix/data/dao/UserDao.java
threadfix-data-access/src/main/java/com/denimgroup/threadfix/data/dao/hibernate/HibernateUserDao.java
threadfix-main/src/main/java/com/denimgroup/threadfix/service/CustomUserDetailServiceImpl.java
threadfix-main/src/main/java/com/denimgroup/threadfix/service/UserServiceImpl.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/AddUserController.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/ChangePasswordController.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/EditUserController.java
threadfix-service-interfaces/src/main/java/com/denimgroup/threadfix/service/UserService.java

Prevent 2 users with same name from being created. If 2 users already exist with same name, handle case and don't throw error.

Dgtf 1536 login with two user with same name ldap and local

---

threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/RemoteProvidersController.java
threadfix-main/src/main/webapp/WEB-INF/views/config/remoteproviders/configure.jsp

Validate API Key field for alphanumeric and hyphen.

Dgtf 1553 undefined error attempting set whitehat remote provider

---

threadfix-main/src/main/webapp/WEB-INF/views/config/emailLists/index.jsp

Adds an ID to the Show/Hide button on Email Lists page that uses the email list name.

added ID to show-hide button for email list page

---

threadfix-main/src/main/webapp/WEB-INF/views/config/emailLists/index.jsp

This adds IDs to the email addresses, delete buttons, input field,, error message, and Add Email button in the showEmailAddresses section below each Email List.  With these IDs a full set of tests can be written.

Added IDs to the elements in showEmailAddresses section

---

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/Vulnerability.java
threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/VulnerabilityComment.java
threadfix-main/src/main/webapp/WEB-INF/views/applications/vulnerability.jsp
threadfix-main/src/main/webapp/WEB-INF/views/reports/progressByVulnerability.jsp
threadfix-main/src/main/webapp/WEB-INF/views/scans/findingDetail.jsp
threadfix-main/src/main/webapp/WEB-INF/views/scans/findingMerge.jsp
threadfix-main/src/main/webapp/WEB-INF/views/tags/commentTable.jsp
threadfix-main/src/main/webapp/WEB-INF/views/tags/vulnTable.jsp
threadfix-main/src/main/webapp/scripts/report/snapshot-report-controller.js
threadfix-main/src/main/webapp/scripts/tag-detail-page-controller.js

Found CWE names, and added CWE number tooltips, to the following pages: Finding Detail, Vulnerability Details, Merge Findings, Remediation, Progress by Vulnerability, Tagged Vulnerabilities, Tagged Vulnerability Comments

Dgtf 1227 add tooltips for cwe numbers

---

threadfix-main/src/main/webapp/WEB-INF/views/vulnerabilities/filterSections.jsp
threadfix-main/src/main/webapp/scripts/report/report-filter-controller.js

Allow Expand/Collapse button to toggle Authentication/Authorization accordion in filter groups.

Dgtf 1502 auth filter group not affected by expand collapse button

---

threadfix-importers/src/main/resources/mappings/scanner/catnet.csv
threadfix-importers/src/main/resources/mappings/scanner/zap.csv

using channel mappings updater to map ZAP severity 4, 5 and Info of CAT.NET

DGTF-1831 Some Scanner Severity Mappings blank by default

---

threadfix-main/src/main/webapp/WEB-INF/views/wafs/index.jsp

This change will make it easier for tests to find WAF page elements quickly.

Changed WAF index page IDs to use WAF name with no spaces

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/modals/manageAcceptanceCriteriaModal.jsp

A few IDs have been added to help tests quickly find elements.

Adds ID to add button and to the criteria listed in modal

---

threadfix-data-access/src/main/java/com/denimgroup/threadfix/data/dao/hibernate/VulnerabilitySearchCriteriaConstructor.java
threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/VulnerabilitySearchParameters.java
threadfix-main/src/main/webapp/WEB-INF/views/vulnerabilities/filterSections.jsp
threadfix-main/src/main/webapp/scripts/report/report-filter-controller.js
threadfix-main/src/main/webapp/scripts/vuln-search-controller.js

Now available in App, Team Detail and Analytic Vuln Search pages

DGTF-1684 Add filtering on comments

---

threadfix-main/src/main/webapp/common/header.jsp

Changes ID for email lists link

---

threadfix-main/src/main/webapp/WEB-INF/views/config/remoteproviders/tabs/remoteProvidersTab.jsp

This update will help resolve test failures by providing universal IDs.

Updated IDs on page to use remote provider names

---

threadfix-main/src/main/webapp/scripts/left-report-controller.js

hasResultsFilter was failing if scan[customSeverityService.getCustomSeverity()] was NaN.

dgtf-1954-saving-trending-report-filter-as-default-hides-vulnerability-trending-reports

---

threadfix-main/src/main/java/com/denimgroup/threadfix/service/EmailListServiceImpl.java

Rename object on delete. Check if isActive when checking nameExists.

DGTF-1787 Cannot create Email List with the name of a deleted list

---

threadfix-main/src/main/webapp/scripts/report/report-services.js

Couldn't redo on dev or stable, instead found out a bug when set time range for trending report, then trending report doesn't get rendered. (for both dev and stable-bugfix)

DGTF-2002 Apps with No Scans Show Data in Vulnerability Trending 

---

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/Vulnerability.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/FindingsController.java
threadfix-main/src/main/webapp/WEB-INF/views/applications/vulnerability.jsp
threadfix-main/src/main/webapp/WEB-INF/views/scans/finding/editDescriptionFindingForm.jsp
threadfix-main/src/main/webapp/WEB-INF/web.xml
threadfix-main/src/main/webapp/scripts/vulnerability-detail-page-controller.js

Same place with Edit Manual Finding (Vulnerability detail page)

DGTF-1604 Add description editing to scanner found vulnerability.

---

threadfix-main/src/main/webapp/scripts/add-to-existing-defect-controller.js

Set placeholder for Defect ID.

dgtf-1970-no-options-listed-when-adding-to-existing-defects

---

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/PolicyStatus.java
threadfix-main/src/main/java/com/denimgroup/threadfix/webapp/controller/APIKeyController.java
threadfix-main/src/main/webapp/WEB-INF/views/config/keys/index.jsp
threadfix-main/src/main/webapp/WEB-INF/views/config/keys/newForm.jsp
threadfix-main/src/main/webapp/WEB-INF/views/config/users/community/index.jsp
threadfix-main/src/main/webapp/scripts/api-keys-controller.js
threadfix-main/src/main/webapp/scripts/user-page-controller.js

Now user can be assigned to API when create new from API keys page, editing still the same

DGTF-1883 Allow assignment of API keys to users from API keys page

---

threadfix-main/src/main/webapp/WEB-INF/views/vulnerabilities/filterSections.jsp

This change allows the test suite to find these elements by their ID.

Removed numbers from front of IDs

---

threadfix-main/src/test/java/com/denimgroup/threadfix/service/defects/BugzillaTests.java
threadfix-main/src/test/java/com/denimgroup/threadfix/service/defects/TFSTests.java
threadfix-main/src/test/java/com/denimgroup/threadfix/service/defects/mock/TFSClientMock.java

These changes should resolve the MergeDevToDevQA build failure, allowing the recent dev changes to make it into dev-qa.

Updates paths used in imports

---

threadfix-main/src/main/java/com/denimgroup/threadfix/service/eventmodel/aspect/DefectEventTrackingAspect.java

…ing for in emitUpdateDefectStatusEvent in DefectEventTrackingAspect. This prevents the creation of duplicate Events.

DGTF-2016 Defect "Close" and "Update Status" Events Register Multiple Times When Defect Contains Multiple Vulnerabilities

---

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/Policy.java

DGTF-2042 Policies page does not enforce character limit on email addresses

---

threadfix-importers/src/main/java/com/denimgroup/threadfix/service/merge/ApplicationMergerImpl.java
threadfix-importers/src/main/java/com/denimgroup/threadfix/service/merge/RemappingServiceImpl.java
threadfix-importers/src/main/java/com/denimgroup/threadfix/service/merge/VulnerabilityParser.java
threadfix-main/src/main/java/com/denimgroup/threadfix/service/ScanDeleteServiceImpl.java
threadfix-main/src/main/java/com/denimgroup/threadfix/service/eventmodel/aspect/VulnerabilityEventTrackingAspect.java
threadfix-service-interfaces/src/main/java/com/denimgroup/threadfix/service/VulnerabilityStatusService.java
threadfix-service-interfaces/src/main/java/com/denimgroup/threadfix/service/impl/VulnerabilityStatusServiceImpl.java

…ntTrackingAspect to not store scan upload Events when remapping findings.

DGTF-2065 Events say scans were uploaded when mapping channel vulnerability types to CWEs

---

threadfix-importers/src/main/java/com/denimgroup/threadfix/importer/impl/upload/ArachniChannelImporter.java

Arachni scans with xml version 1.x have different tags than 0.x for Request and Response.

DGTF-1712 Arachni Scans' Attack Responses are Displayed Incorrectly

---

threadfix-main/src/main/webapp/scripts/vulnerability-detail-page-controller.js

Add successMessage if comment updated.

DGTF-1644 Updating comment on vuln detail does not show success message

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/forms/addDTForm.jsp
threadfix-main/src/main/webapp/WEB-INF/views/config/defecttrackers/modals/createDTModal.jsp
threadfix-main/src/main/webapp/WEB-INF/views/config/defecttrackers/modals/editDTModal.jsp

Adding this ID will help resolve some timing issues in the test suite.

Adds an ID to the section of the modal that receives the ng-hide class

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/vulnerability.jsp

Just a minor change to assist the test suite.

Adds an ID to the Add Comment button

---

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/ScheduledJob.java

 DGTF-2083 Scheduled Email Reports display 12:00 as 0:00

---

threadfix-main/src/main/webapp/WEB-INF/views/config/scheduledemailreports/index.jsp

These will make testing much easier for the page.

Added IDs to the basic elements of the page

---

threadfix-main/src/main/webapp/WEB-INF/views/config/remoteproviders/tabs/remoteProvidersTab.jsp

This will help tests with validation.

Adds IDs to the success and error messages for remote providers

---

threadfix-main/src/main/webapp/WEB-INF/views/organizations/detail.jsp

This will help get rid of some LinkText and PartialLinkText element lookups in the test suite.

Adds IDs to the tabs on the Team Detail page

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/vulnerability.jsp

If you cannot update Vuln, then prevent update of Finding Desc.

DGTF-2173 User with no permission can edit description from Vulnerability Page

---

threadfix-main/src/main/webapp/WEB-INF/views/scans/finding/editManualFindingForm.jsp

This allows the three elements on the page to be accessed by tests freely.

Changes IDs to be unique

---

threadfix-importers/src/main/java/com/denimgroup/threadfix/importer/impl/upload/AppScanWebImporter.java

Display description of issue type into scan recommendation of finding

DGTF-2279 More information from AppScan

---

threadfix-main/src/main/webapp/scripts/report/directives/d3-trending-scans.js

Now, filter which version is in trending range

DGTF-2306 Version markers can extend outside of the Trending report

---

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/ScanImportStatus.java
threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/ScannerDatabaseNames.java
threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/ScannerType.java
threadfix-importers/src/main/java/com/denimgroup/threadfix/importer/impl/upload/AppSpiderChannelImporter.java

Now TF will ask user to upload the VulnerabilitiesSummary.xml

DGTF-2340 Handle new AppSpider format

---

threadfix-main/src/main/webapp/scripts/report/directives/d3-trending-scans.js

DGTF-2365 Version names allow to render HTML

---

threadfix-main/src/main/webapp/velocityTemplates/defectDescription.vm

This includes changing the Vulnerability Index so that it increments, including a header section for Custom Text if any was submitted, and correctly checking for JIRA's name in the conditional statements.

Updates velocity template for defect submission

---

threadfix-main/src/main/webapp/WEB-INF/views/config/defecttrackers/modals/createDTModal.jsp
threadfix-main/src/main/webapp/WEB-INF/views/config/defecttrackers/modals/editDTModal.jsp
threadfix-main/src/main/webapp/decorators/default.jsp
threadfix-main/src/main/webapp/scripts/create-edit-defect-tracker-modal-controller.js
threadfix-main/src/main/webapp/scripts/inputDropdown.js
threadfix-main/src/main/webapp/scripts/threadfix-module.js
threadfix-main/src/main/webapp/styles/inputDropdownStyles.css

Also, implemented dropdown for product names

DGTF-2367 Defect Tracker product select renders HTML

---

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/GenericSeverity.java
threadfix-main/src/main/webapp/WEB-INF/views/organizations/applicationsTable.jsp
threadfix-main/src/main/webapp/WEB-INF/views/organizations/indexTable.jsp
threadfix-main/src/main/webapp/WEB-INF/views/scans/history.jsp
threadfix-main/src/main/webapp/WEB-INF/views/tags/commentTable.jsp
threadfix-main/src/main/webapp/scripts/report/report-services.js
threadfix-main/src/main/webapp/styles/main.css

Now only allow up to 50 characters custom name, and breaks words if they are long

DGTF-2327 Handle exceptionally long Custom Severity Names gracefully

---

threadfix-main/src/main/webapp/WEB-INF/views/applications/forms/manageVersionsForm.jsp

This adds a few IDs and edits one to help the test suite provide coverage for this feature.

Adds IDs to the Manage Versions modal

---

threadfix-main/src/main/webapp/WEB-INF/views/organizations/indexTable.jsp
threadfix-main/src/main/webapp/scripts/applications-index-controller.js

Add search app global, remove search app for each team

DGTF-2463 Add search for all applications on application index page

---

threadfix-entities/src/main/java/com/denimgroup/threadfix/data/entities/Application.java
threadfix-main/src/main/webapp/WEB-INF/views/applications/forms/editApplicationForm.jsp

added project name to link for defect tracker on the application edit modal

DGTF-2487 added project name to link for defect tracker

---

threadfix-main/src/main/webapp/WEB-INF/views/config/systemSettings.jsp

indicate processing while checking ldap connection

DGTF-2522 indicate processing while checking ldap connection

---

threadfix-main/src/main/webapp/WEB-INF/views/filters/channelFilterForm.jsp

Allow the user to press enter to select an option from the autocomplete

DGTF-2492 allow a user to press enter for a typeahead

---

threadfix-main/src/main/webapp/scripts/application-page-modal-controller.js

The edit application modal will no longer appear in front of the create waf modal

DGTF-2654 Fixed for create waf modal

---

threadfix-main/src/main/webapp/WEB-INF/views/config/users/common/userDetails.jspf

This is part of an effort to make the IDs on the User, Role, and Group pages unique.

Modifies IDs to be unique from role and group pages
